# Generated by Django 4.2.7 on 2023-11-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TATAPALETTE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AWB', models.CharField(max_length=50)),
                ('OrderId', models.CharField(max_length=10)),
                ('ShipmentUploadTime', models.DateField()),
                ('ShipmentOrigin', models.CharField(max_length=200)),
                ('ShipmentStatus', models.CharField(max_length=100)),
                ('ShipmentWeight', models.CharField(max_length=50)),
                ('OrderId_Status', models.BooleanField(default=False)),
            ],
        ),
    ]
