# Generated by Django 5.0 on 2023-12-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team2b', '0002_scriptorderids'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndigoScriptOrderIds',
            fields=[
                ('serial', models.IntegerField(default=0, editable=False, primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('used_at', models.DateTimeField(default=None)),
                ('id', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('extra_details', models.JSONField(default=dict)),
            ],
        ),
        migrations.DeleteModel(
            name='ScriptOrderIds',
        ),
        migrations.AddIndex(
            model_name='indigoscriptorderids',
            index=models.Index(fields=['id'], name='team2b_indi_id_e57bc6_idx'),
        ),
    ]
