# Generated by Django 5.0 on 2023-12-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team2b', '0003_indigoscriptorderids_delete_scriptorderids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indigoscriptorderids',
            name='campaign_name',
            field=models.CharField(default='indigomoddteam2modd', max_length=100),
        ),
        migrations.AlterField(
            model_name='indigoscriptorderids',
            name='used_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='IgpScriptOrderIds',
            fields=[
                ('serial', models.IntegerField(default=0, editable=False, primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(default='igpmodd', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('used_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('extra_details', models.JSONField(default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='team2b_igps_id_6af4e5_idx')],
            },
        ),
    ]
