# Generated by Django 5.0 on 2023-12-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team2b', '0004_alter_indigoscriptorderids_campaign_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkeventcount',
            name='serial',
            field=models.AutoField(default=0, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='igpscriptorderids',
            name='serial',
            field=models.AutoField(default=0, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='indigoscriptorderids',
            name='serial',
            field=models.AutoField(default=0, editable=False, primary_key=True, serialize=False),
        ),
    ]
