# Generated by Django 5.0 on 2023-12-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team2b', '0005_alter_checkeventcount_serial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkeventcount',
            name='serial',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='igpscriptorderids',
            name='id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='igpscriptorderids',
            name='serial',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='indigoscriptorderids',
            name='id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='indigoscriptorderids',
            name='serial',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='igpscriptorderids',
            index=models.Index(fields=['created_at'], name='team2b_igps_created_1c44a4_idx'),
        ),
        migrations.AddIndex(
            model_name='indigoscriptorderids',
            index=models.Index(fields=['created_at'], name='team2b_indi_created_152213_idx'),
        ),
    ]
