# Generated by Django 5.0 on 2023-12-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team2b', '0006_alter_checkeventcount_serial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='igpscriptorderids',
            name='booking_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='igpscriptorderids',
            name='delivered_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='indigoscriptorderids',
            name='booking_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indigoscriptorderids',
            name='departure_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
