# Generated by Django 4.1.2 on 2023-12-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team2b', '0008_mcdeliveryscriptorderids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightInTheBox',
            fields=[
                ('serial', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(default='igpmodd', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=50, unique=True)),
                ('used_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='lightinthebox',
            index=models.Index(fields=['id'], name='team2b_ligh_id_731bc5_idx'),
        ),
    ]
