# Generated by Django 5.0 on 2024-01-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team2b', '0012_dominosindodeliveryscriptorderids_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ostinshopscriptorderids',
            name='extra_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
