# Generated by Django 5.0 on 2024-02-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team2b', '0013_alter_ostinshopscriptorderids_extra_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominosindodeliveryscriptorderids',
            name='order_status',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='dominosindodeliveryscriptorderids',
            name='order_type',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.CreateModel(
            name='OstinShopScriptOrderIdsConstants',
            fields=[
                ('serial', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(default='igpmodd', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=50, unique=True)),
                ('order_status', models.CharField(default=0, max_length=100)),
                ('amount', models.CharField(default=0, max_length=100)),
                ('used_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('extra_details', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='team2b_osti_id_ba3549_idx')],
            },
        ),
    ]
