# Generated by Django 5.0 on 2024-02-02 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team2b', '0014_dominosindodeliveryscriptorderids_order_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OstinShopScriptOrderIdsConstants',
            new_name='HabibScriptOrderIdsConstants',
        ),
        migrations.RenameIndex(
            model_name='habibscriptorderidsconstants',
            new_name='team2b_habi_id_0ad502_idx',
            old_name='team2b_osti_id_ba3549_idx',
        ),
    ]
