# Generated by Django 5.0 on 2024-03-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team2b', '0017_damnrayorderids_mumzworldorderids_pepperfryorderids'),
    ]

    operations = [
        migrations.CreateModel(
            name='MumzworldOrderIds',
            fields=[
                ('serial', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(default='mumzworld', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=50, unique=True)),
                ('used_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('order_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('extra_details', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='team2b_mumz_id_491dd8_idx')],
            },
        ),
    ]
