# Generated by Django 4.2.11 on 2024-03-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team2b', '0018_mumzworldorderids'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripsygamesOrderIds',
            fields=[
                ('serial', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(default='tripsygamesmodd', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=15, unique=True)),
                ('order_status', models.CharField(default=0, max_length=10)),
                ('used_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('extra_details', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='team2b_trip_id_6ecb00_idx')],
            },
        ),
    ]
