# Generated by Django 5.0 on 2024-05-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team2b', '0019_tripsygamesorderids'),
    ]

    operations = [
        migrations.AddField(
            model_name='pepperfryorderids',
            name='used_at_2',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
