# Generated by Django 5.0 on 2024-05-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team2b', '0022_idhelperapps_type_pepperfryorderids_channel_and_more'),
        ('team2b', '0023_pepperfryorderids_channel_pepperfryorderids_network_and_more'),
    ]

    operations = [
    ]
