# Generated by Django 5.0 on 2024-05-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team2b', '0024_merge_20240528_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationids',
            name='type',
            field=models.CharField(default='order_id', max_length=8),
        ),
    ]
