# Generated by Django 5.0 on 2024-06-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team2b', '0026_idhelperapps_team_idhelperapps_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FantossUserIds',
            fields=[
                ('serial', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(default='fantosst2modd', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(blank=True, default='', max_length=100)),
                ('network', models.CharField(blank=True, default='', max_length=100)),
                ('offer_id', models.CharField(blank=True, default='', max_length=100)),
                ('id', models.CharField(max_length=50, unique=True)),
                ('used_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('extra_details', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='team2b_fant_id_92f6af_idx')],
            },
        ),
        migrations.CreateModel(
            name='OkeyvipUserId',
            fields=[
                ('serial', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(default='okeyvipmodd', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(blank=True, default='', max_length=100)),
                ('network', models.CharField(blank=True, default='', max_length=100)),
                ('offer_id', models.CharField(blank=True, default='', max_length=100)),
                ('id', models.CharField(max_length=50, unique=True)),
                ('used_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('extra_details', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='team2b_okey_id_ed7d55_idx')],
            },
        ),
        migrations.CreateModel(
            name='PumaOrderId',
            fields=[
                ('serial', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(default='pumaauto', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(blank=True, default='', max_length=100)),
                ('network', models.CharField(blank=True, default='', max_length=100)),
                ('offer_id', models.CharField(blank=True, default='', max_length=100)),
                ('id', models.CharField(max_length=50, unique=True)),
                ('used_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('extra_details', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='team2b_puma_id_8be778_idx')],
            },
        ),
        migrations.CreateModel(
            name='SephoraOrderId',
            fields=[
                ('serial', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(default='sephoramodd', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(blank=True, default='', max_length=100)),
                ('network', models.CharField(blank=True, default='', max_length=100)),
                ('offer_id', models.CharField(blank=True, default='', max_length=100)),
                ('id', models.CharField(max_length=50, unique=True)),
                ('price', models.CharField(max_length=15)),
                ('used_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('extra_details', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='team2b_seph_id_14f631_idx')],
            },
        ),
    ]
