# Generated by Django 5.0 on 2024-06-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team2b', '0027_fantossuserids_okeyvipuserid_pumaorderid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchoorderidsmining',
            name='channel_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='watchoorderidsmining',
            name='network_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='watchoorderidsmining',
            name='offer_id_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
